# Describes the targets run in continuous integration environment.
#
# Flutter infra uses this file to generate a checklist of tasks to be performed
# for every commit.
#
# The recipes mentioned below refer to those in this repo:
#   https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/
#
# The "flutter_drone" recipe just defers to dev/bots/test.dart in this repo,
# with the shard set according to the "shard" key in this file.
#
# More information at:
#  * https://github.com/flutter/cocoon/blob/main/CI_YAML.md
enabled_branches:
  - master
  - flutter-\d+\.\d+-candidate\.\d+

platform_properties:
  staging_build_linux:
    properties:
      dependencies: >-
        [
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Ubuntu
      cores: "8"
      device_type: none
      ignore_flakiness: "true"
  linux:
    properties:
      dependencies: >-
        [
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Ubuntu
      cores: "8"
      device_type: none
  # The current android emulator config names can be found here:
  # https://chromium.googlesource.com/chromium/src.git/+/HEAD/tools/android/avd/proto
  # You may use those names for the android_virtual_device version. You may find the
  # avd_cipd_version by clicking on the latest available instance and looking for the
  # build_id:<Identifier#> here:
  # https://chrome-infra-packages.appspot.com/p/chromium/tools/android/avd/linux-amd64.
  linux_android_emu:
    properties:
      contexts: >-
        [
          "android_virtual_device"
        ]
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "android_virtual_device", "version": "android_35_google_apis_x64.textpb"},
          {"dependency": "avd_cipd_version", "version": "build_id:8735216702926189361"},
          {"dependency": "open_jdk", "version": "version:17"}
        ]
      os: Ubuntu
      cores: "8"
      device_type: none
      kvm: "1"
  linux_android_emu_34:
    properties:
      contexts: >-
        [
          "android_virtual_device"
        ]
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "android_virtual_device", "version": "android_34_google_apis_x64.textpb"},
          {"dependency": "avd_cipd_version", "version": "build_id:8735216702926189361"},
          {"dependency": "open_jdk", "version": "version:17"}
        ]
      os: Ubuntu
      cores: "8"
      device_type: none
      kvm: "1"
  linux_build_test:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "open_jdk", "version": "version:17"},
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Ubuntu
      cores: "8"
      device_type: none
  linux_android:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "open_jdk", "version": "version:17"},
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Linux
      device_type: "msm8952"

  linux_pixel_7pro:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "open_jdk", "version": "version:17"},
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Linux
      device_type: "Pixel 7 Pro"

  linux_mokey:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "open_jdk", "version": "version:17"},
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Linux
      device_type: "mokey"

  mac:
    properties:
      contexts: >-
        [
          "osx_sdk"
        ]
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      os: Mac-13|Mac-14
      device_type: none
      $flutter/osx_sdk : >-
        {
          "sdk_version": "15a240d"
        }
  mac_arm64:
    properties:
      contexts: >-
        [
          "osx_sdk"
        ]
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      os: Mac-13|Mac-14
      device_type: none
      cpu: arm64
      $flutter/osx_sdk : >-
        {
          "sdk_version": "15a240d"
        }
  mac_benchmark:
    properties:
      contexts: >-
        [
          "osx_sdk"
        ]
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      device_type: none
      mac_model: "Macmini8,1"
      os: Mac-13|Mac-14
      tags: >
        ["devicelab", "hostonly", "mac"]
      $flutter/osx_sdk : >-
        {
          "sdk_version": "15a240d"
        }
  mac_x64:
    properties:
      contexts: >-
        [
          "osx_sdk"
        ]
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      os: Mac-13|Mac-14
      device_type: none
      cpu: x86
      $flutter/osx_sdk : >-
        {
          "sdk_version": "15a240d"
        }
  mac_build_test:
    properties:
      contexts: >-
        [
          "osx_sdk"
        ]
      dependencies: >-
        [
          {"dependency": "ruby", "version": "ruby_3.1-pod_1.13"},
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      os: Mac-13|Mac-14
      device_type: none
      cpu: x86
      $flutter/osx_sdk : >-
        {
          "sdk_version": "15a240d"
        }
  mac_android:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "chrome_and_driver", "version": "version:125.0.6422.141"},
          {"dependency": "open_jdk", "version": "version:17"}
        ]
      os: Mac-13|Mac-14
      cpu: x86
      device_type: "msm8952"
  mac_arm64_android:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "open_jdk", "version": "version:17"}
        ]
      os: Mac-13|Mac-14
      cpu: arm64
      device_type: "msm8952"

  mac_mokey:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "chrome_and_driver", "version": "version:125.0.6422.141"},
          {"dependency": "open_jdk", "version": "version:17"}
        ]
      os: Mac-13|Mac-14
      cpu: x86
      device_type: "mokey"
  mac_arm64_mokey:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "open_jdk", "version": "version:17"}
        ]
      os: Mac-13|Mac-14
      cpu: arm64
      device_type: "mokey"

  mac_pixel_7pro:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "open_jdk", "version": "version:17"}
        ]
      os: Mac-13|Mac-14
      cpu: x86
      device_type: "Pixel 7 Pro"
  mac_ios:
    properties:
      contexts: >-
        [
          "osx_sdk_devicelab"
        ]
      dependencies: >-
        [
          {"dependency": "ruby", "version": "ruby_3.1-pod_1.13"},
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      os: Mac-13|Mac-14
      cpu: x86
      device_os: iOS-17
      $flutter/osx_sdk : >-
        {
          "sdk_version": "15a240d"
        }
  mac_x64_ios:
    properties:
      contexts: >-
        [
          "osx_sdk_devicelab"
        ]
      dependencies: >-
        [
          {"dependency": "ruby", "version": "ruby_3.1-pod_1.13"},
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      os: Mac-13|Mac-14
      cpu: x86
      device_os: iOS-17
      $flutter/osx_sdk : >-
        {
          "sdk_version": "15a240d"
        }
  mac_arm64_ios:
    properties:
      contexts: >-
        [
          "osx_sdk_devicelab"
        ]
      dependencies: >-
        [
          {"dependency": "ruby", "version": "ruby_3.1-pod_1.13"},
          {"dependency": "apple_signing", "version": "none"}
        ]
      os: Mac-13|Mac-14
      cpu: arm64
      device_os: iOS-17
      $flutter/osx_sdk : >-
        {
          "sdk_version": "15a240d"
        }
  windows:
    properties:
      os: Windows-10
      device_type: none
  windows_arm64:
    properties:
      # The arch can be removed after https://github.com/flutter/flutter/issues/135722.
      arch: arm
      os: Windows
      cpu: arm64
  windows_android:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "chrome_and_driver", "version": "version:125.0.6422.141"},
          {"dependency": "open_jdk", "version": "version:17"}
        ]
      os: Windows-10
      device_type: "msm8952"
  windows_mokey:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "chrome_and_driver", "version": "version:125.0.6422.141"},
          {"dependency": "open_jdk", "version": "version:17"}
        ]
      os: Windows-10
      device_type: "mokey"

targets:
  - name: Linux build_tests_3_5
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:34v3"},
          {"dependency": "chrome_and_driver", "version": "version:125.0.6422.141"},
          {"dependency": "open_jdk", "version": "version:17"},
          {"dependency": "goldctl", "version": "git_revision:2387d6fff449587eecbb7e45b2692ca0710b63b9"},
          {"dependency": "clang", "version": "git_revision:5d5aba78dbbee75508f01bcaa69aedb2ab79065a"},
          {"dependency": "cmake", "version": "build_id:8787856497187628321"},
          {"dependency": "ninja", "version": "version:1.9.0"}
        ]
      shard: build_tests
      subshard: "3_5"
      tags: >
        ["framework", "hostonly", "shard", "linux"]

  - name: Linux realm_checker
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      add_recipes_cq: "true"
      shard: realm_checker
      tags: >
        ["framework", "hostonly", "shard", "linux"]
    runIf:
      - dev/**
      - packages/flutter_tools/**
      - bin/**
      - .ci.yaml

  - name: Linux run_debug_test_linux
    recipe: devicelab/devicelab_drone
    timeout: 60
    properties:
      xvfb: "1"
      dependencies: >-
        [
          {"dependency": "clang", "version": "git_revision:5d5aba78dbbee75508f01bcaa69aedb2ab79065a"},
          {"dependency": "cmake", "version": "build_id:8787856497187628321"},
          {"dependency": "ninja", "version": "version:1.9.0"}
        ]
      tags: >
        ["devicelab", "hostonly", "linux"]
      task_name: run_debug_test_linux
    runIf:
      - dev/**
      - packages/flutter_tools/**
      - bin/**
      - .ci.yaml

  - name: Linux run_release_test_linux
    recipe: devicelab/devicelab_drone
    timeout: 60
    properties:
      xvfb: "1"
      dependencies: >-
        [
          {"dependency": "clang", "version": "git_revision:5d5aba78dbbee75508f01bcaa69aedb2ab79065a"},
          {"dependency": "cmake", "version": "build_id:8787856497187628321"},
          {"dependency": "ninja", "version": "version:1.9.0"}
        ]
      tags: >
        ["devicelab", "hostonly", "linux"]
      task_name: run_release_test_linux
    runIf:
      - dev/**
      - packages/flutter_tools/**
      - bin/**
      - .ci.yaml

  - name: Linux skp_generator
    enabled_branches:
      - main
      - master
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      shard: skp_generator
      subshard: "0"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
    runIf:
      - dev/**
      - packages/flutter/**
      - packages/flutter_tools/**
      - bin/**
      - .ci.yaml
